---
- name: install uuidgen
  ansible.builtin.apt: name=uuid-runtime

- name: add the netdata signing key
  ansible.builtin.apt_key:
    url: https://packagecloud.io/netdata/netdata/gpgkey
    keyring: /usr/share/keyrings/netdata-archive-keyring.gpg

- name: add netdata repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/netdata-archive-keyring.gpg]
      https://packagecloud.io/netdata/netdata/debian {{ ansible_distribution_release }} main
    filename: netdata
    update_cache: true

- name: install netdata
  ansible.builtin.apt: name=netdata

- name: opt out of analytics
  ansible.builtin.command:
    cmd: touch /etc/netdata/.opt-out-from-anonymous-statistics
    creates: /etc/netdata/.opt-out-from-anonymous-statistics
  notify:
    - restart netdata

- name: ensure netdata is started and enabled
  ansible.builtin.systemd: name=netdata.service state=started enabled=true

- name: get running agent information
  ansible.builtin.command: netdatacli aclk-state json
  register: netdata_agent_info
  changed_when: netdata_agent_info.rc != 0
  failed_when: netdata_agent_info.rc != 0

- name: set claimed status
  ansible.builtin.set_fact:
    netdata_agent_is_claimed: "{{ netdata_agent_info.stdout | from_json | json_query('\"agent-claimed\"') }}"

- name: claim node if it's unclaimed
  when: not netdata_agent_is_claimed
  ansible.builtin.command: netdata-claim.sh -token="{{ netdata_claim_token }}"
  notify:
    - restart netdata
