---
- name: install apache
  ansible.builtin.apt:
    name:
      - apache2
      - ssl-cert

- name: enable apache mod_ssl
  ansible.builtin.file:
    dest: /etc/apache2/mods-enabled/{{ item }}
    src: /etc/apache2/mods-available/{{ item }}
    state: link
  loop:
    - ssl.conf
    - ssl.load
    - socache_shmcb.load
    - headers.load
  notify:
    - restart apache

- name: copy cloudflare origin certificate
  ansible.builtin.copy:
    dest: /etc/ssl/private/pkgs.finelli.dev.{{ item }}
    src: ssl.{{ item }}
    owner: root
    group: ssl-cert
    mode: 0640
  loop:
    - key
    - pem
  notify:
    - restart apache

- name: allow port 443 through the firewall
  community.general.ufw: rule=allow port=443 proto=tcp

- name: ensure pkgs.finelli.dev directory
  ansible.builtin.file:
    path: /srv/pkgs.finelli.dev
    owner: mario # would probably better to use root and a dedicated group...
    group: mario
    mode: 0755 # ...and then 0775
    state: directory

- name: create package directory
  ansible.builtin.file:
    path: /srv/pkgs.finelli.dev/{{ item }}
    owner: mario
    group: mario
    mode: 0755
    state: directory
  loop:
    - arch
    - arch/x86_64

- name: copy virtual host config
  ansible.builtin.copy:
    src: vhost.conf
    dest: /etc/apache2/sites-available/000-pkgsfinellidev.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache

- name: remove default virtual host
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache

- name: link virtual host to enabled
  ansible.builtin.file:
    src: /etc/apache2/sites-available/000-pkgsfinellidev.conf
    dest: /etc/apache2/sites-enabled/000-pkgsfinellidev.conf
    state: link

- name: ensure apache is running and enabled
  ansible.builtin.systemd: name=apache2.service state=started enabled=yes
